server:
  port: 9192
  error:
    include-message: always
spring:
  application:
    name: emailservice
  mail:
    host: smtp.gmail.com
    password: hellosrilanka
    username: chazooltopup@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000








# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory


